In [1]:
import numpy as np
import numpy.linalg as lng

In [85]:
#n>m
A = np.array([[1,2,3],[2,4,6]])
Ainv = lng.pinv(A)
print(Ainv)

A1 = np.dot(A.T, A)
display(A1)

A2 = np.dot(A, A.T)
display(A2)

AleftInv =  np.dot(lng.pinv(np.dot(A.T, A)), A.T)
ArightInv = np.dot(A.T,lng.pinv(np.dot(A, A.T)))
print(AleftInv)
print(ArightInv)

[[ 0.01428571  0.02857143]
 [ 0.02857143  0.05714286]
 [ 0.04285714  0.08571429]]


array([[ 5, 10, 15],
       [10, 20, 30],
       [15, 30, 45]])

array([[14, 28],
       [28, 56]])

[[ 0.01428571  0.02857143]
 [ 0.02857143  0.05714286]
 [ 0.04285714  0.08571429]]
[[ 0.01428571  0.02857143]
 [ 0.02857143  0.05714286]
 [ 0.04285714  0.08571429]]


In [86]:
print(np.dot(A,Ainv))       #right inverse
print(np.dot(Ainv, A))     #left inverse

[[ 0.2  0.4]
 [ 0.4  0.8]]
[[ 0.07142857  0.14285714  0.21428571]
 [ 0.14285714  0.28571429  0.42857143]
 [ 0.21428571  0.42857143  0.64285714]]


In [87]:
#n<m
B = A.T
print(B)
Binv = lng.pinv(B)
print(Binv)

[[1 2]
 [2 4]
 [3 6]]
[[ 0.01428571  0.02857143  0.04285714]
 [ 0.02857143  0.05714286  0.08571429]]


In [88]:
print(np.dot(B, Binv))   #right inverse
print(np.dot(Binv, B))   #left inverse

[[ 0.07142857  0.14285714  0.21428571]
 [ 0.14285714  0.28571429  0.42857143]
 [ 0.21428571  0.42857143  0.64285714]]
[[ 0.2  0.4]
 [ 0.4  0.8]]
